"""Pure-torch log-prob gathering — the part of the policy adapter where the bugs live.

Separated from ``HFPolicy`` because it needs no ``transformers``, no GPU and no model, so it can be
tested exhaustively on a laptop. That matters more here than anywhere else in the phase: **a
wrongly-masked loss still trains.** Every curve looks plausible, the numbers are all finite, and the
run is measuring something other than what it claims.

Two things go wrong in practice, and both are silent:

1. **The off-by-one.** In a causal LM, ``logits[:, t]`` predicts ``token_ids[:, t+1]``. Scoring
   ``token_ids[:, t]`` with ``logits[:, t]`` is off by one position and still produces a perfectly
   reasonable-looking number.
2. **Masking the wrong span.** Prompt tokens must contribute nothing — the policy did not choose
   them — and neither must right-padding after an early EOS.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import torch


def build_completion_mask(
    prompt_len: int, completion_lens: Sequence[int], total_len: int
) -> Any:
    """``[batch, total_len]`` float mask marking the tokens the policy actually chose.

    Assumes **left-padded prompts**, so every sequence's completion begins at the same index —
    which is exactly why generation left-pads. ``completion_lens`` is per-sequence because
    sequences finish at different points.
    """
    if prompt_len < 0:
        raise ValueError("prompt_len must be non-negative")
    mask = torch.zeros(len(completion_lens), total_len)
    for row, n in enumerate(completion_lens):
        if n < 0 or prompt_len + n > total_len:
            raise ValueError(f"completion of {n} tokens does not fit row {row}")
        mask[row, prompt_len : prompt_len + n] = 1.0
    return mask


def completion_logprobs(logits: Any, token_ids: Any, completion_mask: Any) -> Any:
    """Summed log-prob of each sequence's **completion** tokens. Shape ``[batch]``.

    Args:
        logits: ``[batch, seq, vocab]`` over the full prompt+completion sequence.
        token_ids: ``[batch, seq]`` the full sequence.
        completion_mask: ``[batch, seq]`` 1 where a token was generated by the policy.

    The shift is the whole point:

    - ``logits[:, :-1]`` are the predictions *for* ``token_ids[:, 1:]``.
    - The mask is shifted with them, so a completion token at position ``p`` is scored by the
      logits at ``p-1`` — the context that actually produced it.

    A completion beginning at position 0 has no preceding context and is therefore dropped by the
    shift. That is correct: there is no distribution to score its first token against.
    """
    if logits.shape[:2] != token_ids.shape:
        raise ValueError(f"logits {tuple(logits.shape)} do not match ids {tuple(token_ids.shape)}")
    if completion_mask.shape != token_ids.shape:
        raise ValueError("completion_mask must match token_ids")

    shifted_logits = logits[:, :-1, :]
    shifted_ids = token_ids[:, 1:]
    shifted_mask = completion_mask[:, 1:].to(shifted_logits.dtype)

    token_logprobs = (
        torch.log_softmax(shifted_logits, dim=-1)
        .gather(-1, shifted_ids.unsqueeze(-1))
        .squeeze(-1)
    )
    return (token_logprobs * shifted_mask).sum(dim=-1)


def sequence_kl(
    policy_logits: Any, reference_logits: Any, token_ids: Any, completion_mask: Any
) -> Any:
    """Per-sequence KL to the reference, via the **k3** estimator. Shape ``[batch]``.

    ``k3(r) = r − log r − 1`` where ``r = π_ref/π_θ`` on the sampled token. Unbiased and
    **non-negative by construction**, unlike the naive ``log π_θ − log π_ref``, which is unbiased
    but can go negative on a single sample and is much higher variance. This is the estimator GRPO
    uses.
    """
    policy_lp = completion_logprobs(policy_logits, token_ids, completion_mask)
    reference_lp = completion_logprobs(reference_logits, token_ids, completion_mask)
    log_ratio = reference_lp - policy_lp
    return torch.exp(log_ratio) - log_ratio - 1.0


def entropy_over_completions(logits: Any, completion_mask: Any) -> float:
    """Mean per-token entropy over completion positions only.

    Ablation **B**'s slower-moving diversity signal. Prompt positions are excluded because the
    policy's uncertainty there says nothing about what it chose to generate.
    """
    shifted_logits = logits[:, :-1, :]
    shifted_mask = completion_mask[:, 1:].to(shifted_logits.dtype)
    log_probs = torch.log_softmax(shifted_logits, dim=-1)
    per_position = -(log_probs.exp() * log_probs).sum(dim=-1)
    total = shifted_mask.sum()
    if float(total) == 0.0:
        return 0.0
    return float(((per_position * shifted_mask).sum() / total).item())
