"""Pure-torch log-prob gathering — the part of the policy adapter where the bugs live.

Separated from ``HFPolicy`` because it needs no ``transformers``, no GPU and no model, so it can be
tested exhaustively on a laptop. That matters more here than anywhere else in the phase: **a
wrongly-masked loss still trains.** Every curve looks plausible, the numbers are all finite, and the
run is measuring something other than what it claims.

Two things go wrong in practice, and both are silent:

1. **The off-by-one.** In a causal LM, ``logits[:, t]`` predicts ``token_ids[:, t+1]``. Scoring
   ``token_ids[:, t]`` with ``logits[:, t]`` is off by one position and still produces a perfectly
   reasonable-looking number.
2. **Masking the wrong span.** Prompt tokens must contribute nothing — the policy did not choose
   them — and neither must right-padding after an early EOS.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import torch


def build_completion_mask(
    prompt_len: int, completion_lens: Sequence[int], total_len: int
) -> Any:
    """``[batch, total_len]`` float mask marking the tokens the policy actually chose.

    Assumes **left-padded prompts**, so every sequence's completion begins at the same index —
    which is exactly why generation left-pads. ``completion_lens`` is per-sequence because
    sequences finish at different points.
    """
    if prompt_len < 0:
        raise ValueError("prompt_len must be non-negative")
    mask = torch.zeros(len(completion_lens), total_len)
    for row, n in enumerate(completion_lens):
        if n < 0 or prompt_len + n > total_len:
            raise ValueError(f"completion of {n} tokens does not fit row {row}")
        mask[row, prompt_len : prompt_len + n] = 1.0
    return mask


def completion_logprobs(logits: Any, token_ids: Any, completion_mask: Any) -> Any:
    """Summed log-prob of each sequence's **completion** tokens. Shape ``[batch]``.

    Args:
        logits: ``[batch, seq, vocab]`` over the full prompt+completion sequence.
        token_ids: ``[batch, seq]`` the full sequence.
        completion_mask: ``[batch, seq]`` 1 where a token was generated by the policy.

    The shift is the whole point:

    - ``logits[:, :-1]`` are the predictions *for* ``token_ids[:, 1:]``.
    - The mask is shifted with them, so a completion token at position ``p`` is scored by the
      logits at ``p-1`` — the context that actually produced it.

    A completion beginning at position 0 has no preceding context and is therefore dropped by the
    shift. That is correct: there is no distribution to score its first token against.
    """
    if logits.shape[:2] != token_ids.shape:
        raise ValueError(f"logits {tuple(logits.shape)} do not match ids {tuple(token_ids.shape)}")
    if completion_mask.shape != token_ids.shape:
        raise ValueError("completion_mask must match token_ids")

    token_logprobs, mask = _token_logprobs(logits, token_ids, completion_mask)
    if token_logprobs.shape[-1] == 0:
        return torch.zeros(logits.shape[0], device=logits.device, dtype=token_logprobs.dtype)
    return (token_logprobs * mask.to(token_logprobs.dtype)).sum(dim=-1)


def completion_span(completion_mask: Any) -> tuple[int, int] | None:
    """``[start, end)`` column range that any row marks, or ``None`` if nothing is marked.

    Used to slice away the prompt before any full-vocabulary operation. With a 128k vocabulary a
    ``[batch, seq, vocab]`` tensor is gigabytes, and typically ~80% of those positions are prompt
    that we never score — the model must *attend* over them, but nothing needs their distribution.
    """
    columns = completion_mask.sum(dim=0).nonzero().flatten()
    if columns.numel() == 0:
        return None
    return int(columns[0]), int(columns[-1]) + 1


def _token_logprobs(logits: Any, token_ids: Any, completion_mask: Any) -> tuple[Any, Any]:
    """Per-token log-probs over the completion span only, plus the matching mask slice.

    Two memory decisions, both forced by the 128k vocabulary:

    1. **Slice to the completion span first.** Scoring position ``p`` needs the logits at ``p-1``,
       so the slice starts one position early.
    2. **``gather`` minus ``logsumexp`` rather than ``log_softmax``**, since
       ``log_softmax(x)[i] == x[i] - logsumexp(x)``. This avoids materialising a second full
       ``[batch, span, vocab]`` tensor that would immediately be discarded by the gather.
    """
    span = completion_span(completion_mask)
    if span is None:
        empty = logits[:, :0, 0]
        return empty, empty

    start, end = span
    lo = max(0, start - 1)
    sliced = logits[:, lo : end - 1, :]
    ids = token_ids[:, lo + 1 : end]
    mask = completion_mask[:, lo + 1 : end]

    selected = sliced.gather(-1, ids.unsqueeze(-1)).squeeze(-1)
    return selected - torch.logsumexp(sliced, dim=-1), mask


def sequence_kl(
    policy_logits: Any, reference_logits: Any, token_ids: Any, completion_mask: Any
) -> Any:
    """KL to the reference, **k3 applied per token** then summed. Shape ``[batch]``.

    ``k3(r) = r − log r − 1`` where ``r = π_ref/π_θ``. Unbiased and **non-negative by
    construction**, unlike the naive ``log π_θ − log π_ref``, which is unbiased but goes negative
    on single samples and has much higher variance.

    **Per token, not per sequence — and the difference is not cosmetic.** A sequence-level ratio is
    a *product* over tokens, so ``log_ratio`` accumulates and ``exp`` of it compounds
    multiplicatively: a modest 1.2-nat drift per token over 10 tokens gives a per-token KL of ~10.7
    but a sequence-level one of ~1.3e5, and that single sequence would swamp the entire batch loss.
    This is the same compounding that makes sequence-level importance ratios unusable. Per-token is
    also the published GRPO form, so it is what a comparison against ``trl`` would match.
    """
    if policy_logits.shape != reference_logits.shape:
        raise ValueError("policy and reference logits must have the same shape")

    reference_lp, mask = _token_logprobs(reference_logits, token_ids, completion_mask)
    policy_lp, _ = _token_logprobs(policy_logits, token_ids, completion_mask)
    if policy_lp.shape[-1] == 0:
        return torch.zeros(policy_logits.shape[0], device=policy_logits.device)

    log_ratio = reference_lp - policy_lp
    per_token_kl = torch.exp(log_ratio) - log_ratio - 1.0
    return (per_token_kl * mask.to(per_token_kl.dtype)).sum(dim=-1)


def entropy_over_completions(
    logits: Any, completion_mask: Any, *, entropy_chunk: int = 8
) -> float:
    """Mean per-token entropy over completion positions only.

    Ablation **B**'s slower-moving diversity signal. Prompt positions are excluded because the
    policy's uncertainty there says nothing about what it chose to generate.
    """
    span = completion_span(completion_mask)
    if span is None:
        return 0.0
    start, end = span
    lo = max(0, start - 1)
    # Sliced to the completion span for the same reason as _token_logprobs: entropy over prompt
    # positions is both irrelevant and, at a 128k vocabulary, the bulk of the memory.
    sliced = logits[:, lo : end - 1, :]
    mask = completion_mask[:, lo + 1 : end].to(sliced.dtype)
    if mask.numel() == 0 or float(mask.sum()) == 0.0:
        return 0.0

    # Chunked over the batch. Entropy needs three full [chunk, span, vocab] tensors at once
    # (log_softmax, its exp, their product) and at a 128k vocabulary that is ~2 GB for the whole
    # batch in one go. It runs under no_grad, so each chunk is freed immediately — this is purely
    # a peak-memory decision and changes nothing about the value.
    total, count = 0.0, 0.0
    for lo_row in range(0, sliced.shape[0], entropy_chunk):
        rows = slice(lo_row, lo_row + entropy_chunk)
        log_probs = torch.log_softmax(sliced[rows], dim=-1)
        per_position = -(log_probs.exp() * log_probs).sum(dim=-1)
        total += float((per_position * mask[rows]).sum())
        count += float(mask[rows].sum())
    return total / count if count else 0.0
